### ISSUE TITLE
Kod JS w pliku HTML

### ISSUE THREAD

**Issue by Bogus555** [Resident98/Symulator-ekstraklasy#6]
Jeżeli chodzi o zaimplementowanie skryptów Javascript to prosiłbym was żebyście podłączyli go zewnętrznie, w linku i odwoływali się do funkcji. Żeby nie robić bałaganu w kodzie, oczywiście jeżeli będzie to możliwe.

**Comment by Brudasz** [comment]
No problemo ! taki był plan.
